use_frameworks!

platform :ios, '8.0'

target 'podsSpecs_Example' do
  pod 'podsSpecs', :path => '../'

  target 'podsSpecs_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
